name: build
on: 
  push: 
    branches: 
      - master # 只要push到main分支，就会触发后续流程
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Github官方发布的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3

      # 在工作流中安装node环境
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 指定node版本
          
      # 打包代码生成环境
      - name: Build
        run: |
          cd client # 进入前端侧的工程目录
          npm install # 安装依赖
          npm run build # 打包代码到生产环境（目标路径为：server/public）
